# Generated by Django 4.2 on 2024-11-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Savings', 'Savings'), ('Investment', 'Investment'), ('Debt', 'Debt')], max_length=10),
        ),
    ]
